{
    "affected": [
        {
            "package": {
                "ecosystem": "Debian:10",
                "name": "python-django",
                "purl": "pkg:deb/debian/python-django?distro=buster&repository_url=http%3A%2F%2Fdeb.freexian.com%2Fextended-lts"
            },
            "ranges": [
                {
                    "events": [
                        {
                            "introduced": "0"
                        },
                        {
                            "fixed": "1:1.11.29-1+deb10u12"
                        }
                    ],
                    "type": "ECOSYSTEM"
                }
            ]
        }
    ],
    "database_specific": {
        "type": "security update"
    },
    "id": "ELA-1164-1",
    "modified": "2024-08-27T00:00:00Z",
    "references": [
        {
            "type": "ADVISORY",
            "url": "https://deb.freexian.com/extended-lts/tracker/ELA-1164-1"
        },
        {
            "type": "ADVISORY",
            "url": "https://deb.freexian.com/extended-lts/tracker/CVE-2024-41989"
        },
        {
            "type": "ADVISORY",
            "url": "https://deb.freexian.com/extended-lts/tracker/CVE-2024-41991"
        },
        {
            "type": "ADVISORY",
            "url": "https://deb.freexian.com/extended-lts/tracker/CVE-2024-42005"
        }
    ],
    "related": [
        "CVE-2024-41989",
        "CVE-2024-41991",
        "CVE-2024-42005"
    ]
}