{
    "affected": [
        {
            "package": {
                "ecosystem": "Debian:9",
                "name": "python-django",
                "purl": "pkg:deb/debian/python-django?distro=stretch&repository_url=http%3A%2F%2Fdeb.freexian.com%2Fextended-lts"
            },
            "ranges": [
                {
                    "events": [
                        {
                            "introduced": "0"
                        },
                        {
                            "fixed": "1:1.10.7-2+deb9u27"
                        }
                    ],
                    "type": "ECOSYSTEM"
                }
            ]
        },
        {
            "package": {
                "ecosystem": "Debian:10",
                "name": "python-django",
                "purl": "pkg:deb/debian/python-django?distro=buster&repository_url=http%3A%2F%2Fdeb.freexian.com%2Fextended-lts"
            },
            "ranges": [
                {
                    "events": [
                        {
                            "introduced": "0"
                        },
                        {
                            "fixed": "1:1.11.29-1+deb10u16"
                        }
                    ],
                    "type": "ECOSYSTEM"
                }
            ]
        }
    ],
    "database_specific": {
        "type": "security update"
    },
    "id": "ELA-1535-1",
    "modified": "2025-10-07T00:00:00Z",
    "references": [
        {
            "type": "ADVISORY",
            "url": "https://deb.freexian.com/extended-lts/tracker/ELA-1535-1"
        },
        {
            "type": "ADVISORY",
            "url": "https://deb.freexian.com/extended-lts/tracker/CVE-2025-59681"
        },
        {
            "type": "ADVISORY",
            "url": "https://deb.freexian.com/extended-lts/tracker/CVE-2025-59682"
        }
    ],
    "related": [
        "CVE-2025-59681",
        "CVE-2025-59682"
    ]
}