{
    "affected": [
        {
            "package": {
                "ecosystem": "Debian:8",
                "name": "pymongo",
                "purl": "pkg:deb/debian/pymongo?distro=jessie&repository_url=http%3A%2F%2Fdeb.freexian.com%2Fextended-lts"
            },
            "ranges": [
                {
                    "events": [
                        {
                            "introduced": "0"
                        },
                        {
                            "fixed": "2.7.2-1+deb8u1"
                        }
                    ],
                    "type": "ECOSYSTEM"
                }
            ]
        },
        {
            "package": {
                "ecosystem": "Debian:9",
                "name": "pymongo",
                "purl": "pkg:deb/debian/pymongo?distro=stretch&repository_url=http%3A%2F%2Fdeb.freexian.com%2Fextended-lts"
            },
            "ranges": [
                {
                    "events": [
                        {
                            "introduced": "0"
                        },
                        {
                            "fixed": "3.4.0-1+deb9u1"
                        }
                    ],
                    "type": "ECOSYSTEM"
                }
            ]
        }
    ],
    "database_specific": {
        "type": "security update"
    },
    "id": "ELA-1111-1",
    "modified": "2024-06-17T00:00:00Z",
    "references": [
        {
            "type": "ADVISORY",
            "url": "https://deb.freexian.com/extended-lts/tracker/ELA-1111-1"
        },
        {
            "type": "ADVISORY",
            "url": "https://deb.freexian.com/extended-lts/tracker/CVE-2024-5629"
        }
    ],
    "related": [
        "CVE-2024-5629"
    ]
}