{
    "affected": [
        {
            "package": {
                "ecosystem": "Debian:9",
                "name": "python-tornado",
                "purl": "pkg:deb/debian/python-tornado?distro=stretch&repository_url=http%3A%2F%2Fdeb.freexian.com%2Fextended-lts"
            },
            "ranges": {
                "events": [
                    {
                        "introduced": "0"
                    },
                    {
                        "fixed": "4.4.3-1+deb9u1"
                    }
                ],
                "type": "ECOSYSTEM"
            }
        },
        {
            "package": {
                "ecosystem": "Debian:10",
                "name": "python-tornado",
                "purl": "pkg:deb/debian/python-tornado?distro=buster&repository_url=http%3A%2F%2Fdeb.freexian.com%2Fextended-lts"
            },
            "ranges": {
                "events": [
                    {
                        "introduced": "0"
                    },
                    {
                        "fixed": "5.1.1-4+deb10u1"
                    }
                ],
                "type": "ECOSYSTEM"
            }
        }
    ],
    "database_specific": {
        "type": "security update"
    },
    "id": "ELA-1287-1",
    "modified": "2025-01-11T00:00:00Z",
    "references": [
        {
            "type": "ADVISORY",
            "url": "https://deb.freexian.com/extended-lts/tracker/ELA-1287-1"
        },
        {
            "type": "ADVISORY",
            "url": "https://deb.freexian.com/extended-lts/tracker/CVE-2023-28370"
        },
        {
            "type": "ADVISORY",
            "url": "https://deb.freexian.com/extended-lts/tracker/CVE-2024-52804"
        }
    ],
    "related": [
        "CVE-2023-28370",
        "CVE-2024-52804"
    ]
}